### ISSUE TITLE
Fix chance that anon login will fail by generating already-existing ID

### ISSUE THREAD

**Issue by drusepth** [drusepth/Indent#23]
As seen in

    id = rand(10000000).to_s + rand(10000000).to_s
    @user = User.new(:name => 'Anonymous-' + id.to_s, :email => id.to_s + '@localhost', :password => id.to_s)

**Comment by drusepth** [comment]
This'll probably be easier with sqlite/postgres, since we can rely on the DB to give us an ID instead of having to provide one.

**Comment by Cantido** [comment]
Maybe we could create another table, with some kind of counter? Then we just get the next value from that.

**Comment by drusepth** [comment]
We should be able to just use a UUID, now that I'm thinking about it. Should just be able to do `SecureRandom.uuid`, which is built in to Rails IIRC and guaranteed always unique.

**Comment by Cantido** [comment]
I can't find any documentation that says it is guaranteed to be unique. I
see docs that say it's incredibly unlikely, though. This sounds good unless
there is a solution with zero chance of collision.

**Comment by drusepth** [comment]
Ah. According to [this page](http://stackoverflow.com/questions/1155008/how-unique-is-uuid) version 1 is seeded with an internal clock that will wrap at 3603 A.D., so supposedly every UUID generated until then is guaranteed unique, or at least as far as I understand it.

There's a more in-depth look at how version 1 works [here](http://blogs.msdn.com/b/oldnewthing/archive/2008/06/27/8659071.aspx) :)

I'm no expert and haven't looked into it much, but it looks to be pretty solid for generating random strings.

**Comment by Cantido** [comment]
That sounds perfect then!

**Comment by drusepth** [comment]
Anon logins were rarely used and removed to simplify onboarding on branch `notebook`.
