### ISSUE TITLE
Implement Continuous Deployment to Staging

### ISSUE THREAD

**Issue by Cantido** [drusepth/Indent#337]
Travis can deploy via  a lot of services on a successful build. If you're confident enough in your tests you could consider having it push straight to production but deploying to staging sounds like a pretty safe yet convenient strategy.

[Travis CI Deployment Overview](http://docs.travis-ci.com/user/deployment/)

**Comment by drusepth** [comment]
84% test coverage; looks like it's time to revisit this. The biggest concern I have with continuous deployment is production stability. However, I do think it's a useful thing to have, so I say we lay out some guidelines for the flow and then make it happen.

What do you think about these steps?

Staging:
- [ ] Set up staging environment on EC2
- [ ] On new commits into master (merged pull requests, pushes to master), fire off Travis builds. If all tests pass and we retain >90% code coverage, master is deployed to staging.
- [ ] On staging deploy, data is re-seeded from seed.rb

Production
- [ ] For now, retain manual deployment to production.
- [ ] Eventually, we could probably incorporate New Relic monitoring on staging and say something like if the code has been on staging for X days with no runtime errors, deploy it to production. Would probably need some sort of automation to hit everything on staging that could error (in addition to tests) though.

@streed Do you have any thoughts on this?

**Comment by Cantido** [comment]
We can configure Coveralls to fail the build when coverage gets below a certain threshold, I think. Travis will only execute its `deploy` and `after-success` stages if the tests pass.

We can also define additional steps to migrate/refresh the DB, etc.

**Comment by Cantido** [comment]
Also, since Capybara tests are just so delightful to write (see the functions in [test_helper.rb](https://github.com/drusepth/Indent/blob/master/test/test_helper.rb#L23), that is 100% Capybara DSL), we can very easily write any integration tests we need. The foundation has been laid.

**Comment by Cantido** [comment]
Could you document how you deploy to staging? I can get some of this started. Aside from that, all you'll probably need to do is encrypt your username and password information probably (I don't know how to deploy to EC2 from Travis yet). If you could even just give me the bash script or whatever you use, I can put that into the travis config.

**Comment by Cantido** [comment]
Oh, if you set up Amazon Code Deploy, we can deploy straight to S3 and Amazon will deploy the app from there... I think.

http://docs.aws.amazon.com/codedeploy/latest/userguide/welcome.html
