### ISSUE TITLE
Privacy value not validated for presence

### ISSUE THREAD

**Issue by Cantido** [drusepth/Indent#361]
Since all of the models' Privacy values are not required to be present, any request to show that content could cause the following exception:
````
NoMethodError: undefined method `downcase' for nil:NilClass
    app/controllers/application_controller.rb:215:in `hide_private_character'
    test/controllers/characters_controller_test.rb:34:in `block in <class:CharactersControllerTest>'
````

This is due to [this line][1] for the Universe controller, similar for the other models:

```ruby
unless (session[:user] and session[:user] == character.user.id) or (character.universe and character.universe.privacy.downcase == 'public')
```
which doesn't check the presence of `character.universe.privacy` first. The rest of the privacy checks here have the same problem, I just came across it while debugging the characters controller.

The form to create a universe does provide a default, but since your code is assuming that the value is present, this value should be enforced as not null by the database, or the code should check for nil.

[1]: https://github.com/drusepth/Indent/blob/master/app/controllers/application_controller.rb#L215

**Comment by Cantido** [comment]
So, should we validate presence of the privacy field for all models, or just do a check for null in all the controllers? My vote is for model-layer validation.

**Comment by drusepth** [comment]
I think privacy is a good candidate for a required field. We should probably validate that it exists non-nil on every model since we're relying on it for functionality (showing/hiding content) rather than just storing data in it.

We can probably also validate that its value is only 'public' or 'private'.

**Comment by Cantido** [comment]
I can do some research. Setting fields to a certain default value sounds like something we can do in a migration.

**Comment by Cantido** [comment]
So the controllers actually no longer have this line. This issue is no longer valid.
