### ISSUE TITLE
Fix all the whitespace style errors

### ISSUE THREAD

**Issue by drusepth** [drusepth/Indent#368]
Can we just jshint (or ruby-equivalent) the whole system and fix everything? Whitespace seems like a good place to start. Not a big deal, but pretty code is pretty code.

- [ ] Fix whitespace-at-end-of-line errors
- [ ] Normalize all tabs to spaces (and otherwise conform to github style guidelines)

**Comment by Cantido** [comment]
I found [reek](https://github.com/troessner/reek) which is a "code smell detector" for Ruby. I like the sound of it. I'll do some more research and see if it's something we should add. This code is going to be a work of art.
