### ISSUE TITLE
Implement an authentication gem

### ISSUE THREAD

**Issue by Cantido** [drusepth/Indent#376]
Just suggesting an external gem because it would be more robust than any authentication system we could write on our own. We have a lot of options. I was thinking OpenID, but if that's too big, [Devise](https://github.com/plataformatec/devise) seems like a really popular choice.

Resources:
- [OpenID Developer Specifications](http://openid.net/developers/specs/)
- [Railscast on OpenID in Rails](http://railscasts.com/episodes/68-openid-authentication)

**Comment by drusepth** [comment]
I've done a **lot** of work in Devise over the past 4-5 months and now have a strong preference towards Devise. I'll probably get that cracking soon, hopefully.

Devise also has an omniauth module that'll allow openid/sso providers like Google/Facebook/etc login.

**Comment by Cantido** [comment]
Rails 4 has secure password functionality built-in. We can also consider having this on the site. I do not know anything about Devise so I can't make a preference.

http://api.rubyonrails.org/classes/ActiveModel/SecurePassword.html

**Comment by drusepth** [comment]
Done in https://github.com/drusepth/Indent/pull/432
