### ISSUE TITLE
Migrate from MongoDB to Sqlite3

### ISSUE THREAD

**Issue by drusepth** [drusepth/Indent#380]
Checklist for actually doing the migration:
- [x] Pause adwords from running
- [x] Source `MONGOHQ_URL`
- [x] Put site into maintenance mode
- [x] Export mongo with  `mongodump --host linus.mongohq.com --port 10007 --db indent_prod -u user -p password`
- [x] Convert each collection into json with `bsondump --type json collection.bson > collection.json`
- [x] Strip last three digits off `Date()` values in locations.json
- [x] Check out `migrate-to-sql` branch
- [x] `rake db:create; rake db:migrate`
- [x] Disable User's `before_save :hash_password` in `User.rb`
- [x] Run  `bundle exec rails runner migrate_to_sqlite.rb` to load each json file, create objects, and save to db
- [x] Run test suite in #360 while smoke testing site
- [x] Take site out of maintenance mode
- [x] Resume adwords
- [ ] Disable mongohq account

**Comment by drusepth** [comment]
![its-happening-ron-paul-gif](https://cloud.githubusercontent.com/assets/538235/6660776/ad7e6760-cb6e-11e4-81b2-f932dcb880e4.gif)

**Comment by drusepth** [comment]
We're liiiiiiiiiiive!

**Comment by Cantido** [comment]
WE DONE IT
