### ISSUE TITLE
Track test coverage

### ISSUE THREAD

**Issue by Cantido** [drusepth/Indent#388]
Set up the repo in https://coveralls.io, put another nice badge on the README, optimize our time writing tests. I'll work on this.

[Guide for Rails](https://coveralls.zendesk.com/hc/en-us/articles/201769485-Ruby-Rails)

**Comment by drusepth** [comment]
@Cantido Is this done? Or is there still work to do on it?

**Comment by Cantido** [comment]
Yes! Done as of cb7174067d80a5b91594b595a2b47d9451b26be2
