### ISSUE TITLE
Some locations cannot be edited?

### ISSUE THREAD

**Issue by drusepth** [drusepth/Indent#415]
Looks to be some kind of bug since the release last night. Some existing locations seem not to be able to be edited, and instead just pipe the user back to the edit page with no flashes instead of saving.

It may be related to temporarily disabling the map S3 uploading.

**Comment by drusepth** [comment]
@Cantido Curious, do we have any test cases failing because of this?

**Comment by Cantido** [comment]
No, none yet. I was seriously expecting the Capybara test to fail.

However, seeds.rb cannot seed locations. If you check out the seed file,
you can see that I had to comment the location creation out. So this is an
environment-specific issue. I have a little more info in #416.

**Comment by Cantido** [comment]
I did not connect the dots that installing only non-production gems would cause the app to fail when it needed production gems. Wow.

I have `aws-sdk` in the `:production` group and installed the gems `--without production` so no wonder it was failing for me. I moved it out of the production group and it works just fine for me now. Sorry about that.

**Comment by drusepth** [comment]
Fixed
