### ISSUE TITLE
Harden username and password hashing to length extension attacks

### ISSUE THREAD

**Issue by Cantido** [drusepth/Indent#417]
At line 12, in [sessions_controller.rb][line], the controller concatenates the user's name with their password, and hashes using an MD5 hash. This means that it is possible to use a [length extension attack][wiki] to generate a new hash, and potentially hijack a session, if we use this hash as a secure token. I'm not 100% sure that we are in a situation in which this is a vulnerability, but it's a very small change to protect the site in case this becomes possible in the future.

To fix it, we would just have to slightly modify how we hash, to something like

```ruby
Digest::MD5.hexdigest(login.username + "'s hashed password IS... " + Digest::MD5.hexdigest(login.password) + " (lol!)")
```

[line]: https://github.com/drusepth/Indent/blob/master/app/controllers/sessions_controller.rb#L18
[wiki]: http://en.wikipedia.org/wiki/Length_extension_attack

**Comment by Cantido** [comment]
I can push a fix for this later today. I'm reading a web application security book right now :closed_lock_with_key:

**Comment by LinuxMercedes** [comment]
+1

**Comment by drusepth** [comment]
Done in https://github.com/drusepth/Indent/pull/432
