### ISSUE TITLE
Host documentation online

### ISSUE THREAD

**Issue by Cantido** [drusepth/Indent#418]
Uses git's commit hooks to pull and build documentation, and then host it. It's free.

https://readthedocs.org/

They even give us a cute little badge.

**Comment by drusepth** [comment]
What's the process look like to set this up? Is it just conforming to a certain style in the code, or does it need additional hooks/actions to get going?

**Comment by Cantido** [comment]
So I was assuming this would build our RDoc and host it, but that's not the case. It can compile mkdoc (uses markdown) or Sphinx (a Python utility) in a separate folder structure. Now that I've read this a little more, I think we would both prefer to just stick with the GitHub wiki for now. 

Would we want anything like a new user guide as part of indentapp.com, on the GitHub wiki, or on readthedocs? I'm not sure what kind of docs we would want separate from both the site and GitHub.

**Comment by Cantido** [comment]
We now host docs on [inch-ci.org](https://inch-ci.org/github/drusepth/Indent) as of fd47014ead8e169f7dbf623edb9ab23ddc250077

**Comment by drusepth** [comment]
Thanks for knocking this out.

**Comment by Cantido** [comment]
I found what I was actually looking for!

Inch CI just calculates total coverage and gives us a badge. RubyDoc.info actually builds and hosts documentation. It uses YARD instead of RDoc, however YARD is a superset of RDoc, so it's compatible, and it is documented better. You'll need to set up a commit hook to http://www.rubydoc.info/checkout
