### ISSUE TITLE
Images are stretched at small window widths

### ISSUE THREAD

**Issue by Cantido** [drusepth/Indent#419]
See image at the bottom of this screenshot. The image is stretched horizontally to fill the entire width.

![image](https://cloud.githubusercontent.com/assets/1505603/6766251/919cf98c-cfcc-11e4-9410-8a541445488f.png)

**Comment by drusepth** [comment]
I really want to freelance out a designer for a proper design, I think.

Good catch on this though.

**Comment by drusepth** [comment]
Fixed in redesign
