### ISSUE TITLE
Remove secret_token.rb file

### ISSUE THREAD

**Issue by Cantido** [drusepth/Indent#425]
The [secret_token.rb](https://github.com/drusepth/Indent/blob/master/config/initializers/secret_token.rb) file should not be checked into source control. That's your private key for signing cookies.

As an alternative, you could use travis's command-line utility to encrypt this value, and then add the secret token to the `.travis.yml` file, use that to stick it into an environment variable, and then pull it into this file.

**Comment by drusepth** [comment]
:+1:
