### ISSUE TITLE
Implement a stronger password hashing scheme

### ISSUE THREAD

**Issue by Cantido** [drusepth/Indent#431]
Currently the site uses MD5, which is not cryptographically secure anymore. We also use the user's username as a salt, which is better than nothing, but we can do a lot more with less custom work with the [`bcrypt-ruby` gem](http://bcrypt-ruby.rubyforge.org/) which was made exactly for this sort of thing.

Changing the password-hashing strategy would require some migration work. The easiest way would be to have both strategies active at one time. Whenever a user logs in, we can check their old password field to authenticate. Once we have identified them, we can hash their password into the new algorithm. Then after a period of time, we can force password resets.

**Comment by Cantido** [comment]
Upon more research, Rails 4 has `bcrypt` built in, via [`ActiveRecord::SecurePassword`](http://api.rubyonrails.org/classes/ActiveModel/SecurePassword/ClassMethods.html#method-i-has_secure_password). I'm going to try implementing this on a branch.

**Comment by Cantido** [comment]
The `has_secure_password` methods override the `User.password` field, so I'm going to move the field into `old_password`.

**Comment by drusepth** [comment]
Done in https://github.com/drusepth/Indent/pull/432
